### ISSUE TITLE
调整窗口宽度时，控制台报错

### ISSUE THREAD

**Issue by pangqianjin** [hanzhenfang/auto-ellipsis-text#2]
![image](https://user-images.githubusercontent.com/49555245/230257371-5bf430e3-3305-4d06-94d6-622341c97134.png)

![image](https://user-images.githubusercontent.com/49555245/230257183-e266df6a-bfac-40eb-b28f-3c3193b775e5.png)
![image](https://user-images.githubusercontent.com/49555245/230257292-5e5521b9-9223-4650-9847-203bb8193991.png)

**Comment by hanzhenfang** [comment]
Thanks， I will fix this issue as soon as possible.
